name: C++ CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Change to other OS if needed, like windows-latest or macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the code from your repository

      - name: Set up CMake
        uses: actions/setup-cmake@v2  # Official CMake setup action
        with:
          cmake-version: '3.22'  # Specify your desired CMake version (adjust as necessary)

      - name: Install build dependencies
        run: sudo apt-get install -y g++ make # Installing necessary build tools

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.22'

      - name: Install build dependencies
        run: sudo apt-get install -y g++ make

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest  # Run the tests in your project using CTest
