name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up CMake
      - name: Set up CMake
        uses: scivision/setup-cmake@v1

      # Step 3: Install dependencies (CMake, build tools, etc.)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ git

      # Step 4: Build the project
      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Step 5: Run tests
      - name: Run tests
        run: |
          cd build
          ./tests/project2Test  # Update this with the actual test binary name
