name: C++ CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to your preferred OS like windows-latest or macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the code from your repository

      - name: Set up CMake
        uses: cmake/ctest@v2  # Sets up CMake for building C++ projects

      - name: Install Dependencies
        run: sudo apt-get install -y g++ cmake make  # Install build tools, you can modify for your needs

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y g++ cmake make

      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest  # This runs the tests in your project
